"""
core/analysis/condition_mapper.py

Maps every SCP-ECG code the FCN Wang / PTB-XL model can emit to:
  - Human-readable display name
  - Medical definition (frontend tooltip)
  - Severity tier: "normal" | "warning" | "critical"

All 71 PTB-XL codes are covered so no prediction ever falls back to
"Unclassified Finding" for a known code.
"""

from dataclasses import dataclass
from typing import Literal

SeverityTier = Literal["normal", "warning", "critical"]


@dataclass(frozen=True)
class ConditionInfo:
    code:         str
    display_name: str
    definition:   str
    severity:     SeverityTier


_CONDITION_MAP: dict[str, ConditionInfo] = {

    # ── Normal / benign ────────────────────────────────────────────────────
    "NORM": ConditionInfo("NORM", "Normal ECG",
        "No clinically significant abnormalities detected.", "normal"),

    "SR": ConditionInfo("SR", "Sinus Rhythm",
        "Normal heart rhythm originating from the sinoatrial node.", "normal"),

    "SARRH": ConditionInfo("SARRH", "Sinus Arrhythmia",
        "Normal variation in heart rate with the breathing cycle — common and benign.", "normal"),

    "PACE": ConditionInfo("PACE", "Paced Rhythm",
        "ECG pattern generated by an implanted cardiac pacemaker.", "normal"),

    # ── Sinus node abnormalities ───────────────────────────────────────────
    "SBRAD": ConditionInfo("SBRAD", "Sinus Bradycardia",
        "Slow heart rate (< 60 bpm) originating from the sinoatrial node.", "warning"),

    "STACH": ConditionInfo("STACH", "Sinus Tachycardia",
        "Fast heart rate (> 100 bpm) originating from the sinoatrial node.", "warning"),

    # ── Atrial conditions ─────────────────────────────────────────────────
    "AFIB": ConditionInfo("AFIB", "Atrial Fibrillation",
        "Chaotic, irregular atrial electrical activity causing an irregular ventricular "
        "response and increased stroke risk.", "critical"),

    "AFLT": ConditionInfo("AFLT", "Atrial Flutter",
        "Rapid but organised atrial rhythm (250–350 bpm), often with a regular ventricular response.", "critical"),

    "PAC": ConditionInfo("PAC", "Premature Atrial Contraction",
        "An early heartbeat initiated in the atria outside the sinoatrial node.", "warning"),

    "PSVT": ConditionInfo("PSVT", "Paroxysmal Supraventricular Tachycardia",
        "Sudden-onset rapid heart rate originating above the ventricles.", "warning"),

    "SVARR": ConditionInfo("SVARR", "Supraventricular Arrhythmia",
        "An arrhythmia originating above the bundle of His.", "warning"),

    "SVTAC": ConditionInfo("SVTAC", "Supraventricular Tachycardia",
        "Rapid heart rate (> 100 bpm) with an origin above the ventricles.", "warning"),

    "LAO/LAE": ConditionInfo("LAO/LAE", "Left Atrial Enlargement",
        "Increased left atrial size, often associated with hypertension or mitral valve disease.", "warning"),

    "RAO/RAE": ConditionInfo("RAO/RAE", "Right Atrial Enlargement",
        "Increased right atrial size, often associated with pulmonary hypertension.", "warning"),

    # ── Conduction defects ────────────────────────────────────────────────
    "1AVB": ConditionInfo("1AVB", "First Degree AV Block",
        "Prolonged PR interval (> 200 ms) indicating delayed conduction through the AV node.", "warning"),

    "2AVB": ConditionInfo("2AVB", "Second Degree AV Block",
        "Intermittent failure of atrial impulses to conduct to the ventricles.", "critical"),

    "3AVB": ConditionInfo("3AVB", "Third Degree AV Block",
        "Complete dissociation between atrial and ventricular activity — a medical emergency.", "critical"),

    "LBBB": ConditionInfo("LBBB", "Left Bundle Branch Block",
        "Delayed conduction in the left bundle branch causing wide, abnormal QRS complexes.", "warning"),

    "CLBBB": ConditionInfo("CLBBB", "Complete Left Bundle Branch Block",
        "Complete blockage of the left bundle branch, causing wide QRS > 120 ms with characteristic morphology.", "warning"),

    "ILBBB": ConditionInfo("ILBBB", "Incomplete Left Bundle Branch Block",
        "Partial conduction delay in the left bundle branch with QRS 110–120 ms.", "warning"),

    "RBBB": ConditionInfo("RBBB", "Right Bundle Branch Block",
        "Delayed conduction in the right bundle branch causing the characteristic RSR' pattern.", "warning"),

    "CRBBB": ConditionInfo("CRBBB", "Complete Right Bundle Branch Block",
        "Complete blockage of the right bundle branch with QRS > 120 ms and RSR' pattern.", "warning"),

    "IRBBB": ConditionInfo("IRBBB", "Incomplete Right Bundle Branch Block",
        "Partial right bundle branch delay with QRS 110–120 ms — often a normal variant.", "warning"),

    "LAFB": ConditionInfo("LAFB", "Left Anterior Fascicular Block",
        "Block in the anterior fascicle of the left bundle branch, causing left axis deviation.", "warning"),

    "LPFB": ConditionInfo("LPFB", "Left Posterior Fascicular Block",
        "Block in the posterior fascicle of the left bundle branch, causing right axis deviation.", "warning"),

    "IVCD": ConditionInfo("IVCD", "Intraventricular Conduction Delay",
        "Non-specific conduction delay within the ventricles not meeting LBBB or RBBB criteria.", "warning"),

    "ABQRS": ConditionInfo("ABQRS", "Abnormal QRS",
        "QRS complex morphology that does not fit a specific bundle branch block pattern.", "warning"),

    "WPW": ConditionInfo("WPW", "Wolff-Parkinson-White Syndrome",
        "Pre-excitation syndrome with an accessory pathway causing delta waves and short PR interval.", "critical"),

    # ── Myocardial infarction ─────────────────────────────────────────────
    "AMI": ConditionInfo("AMI", "Acute Myocardial Infarction",
        "Active heart attack with ongoing myocardial injury, shown by ST elevation and evolving Q waves.", "critical"),

    "IMI": ConditionInfo("IMI", "Inferior Myocardial Infarction",
        "Myocardial infarction in the inferior wall, typically involving the right coronary artery territory.", "critical"),

    "ASMI": ConditionInfo("ASMI", "Anteroseptal Myocardial Infarction",
        "Infarction involving the anterior and septal walls of the left ventricle.", "critical"),

    "ALMI": ConditionInfo("ALMI", "Anterolateral Myocardial Infarction",
        "Infarction involving the anterior and lateral walls of the left ventricle.", "critical"),

    "ILMI": ConditionInfo("ILMI", "Inferolateral Myocardial Infarction",
        "Infarction affecting both the inferior and lateral walls of the heart.", "critical"),

    "LMI": ConditionInfo("LMI", "Lateral Myocardial Infarction",
        "Myocardial infarction isolated to the lateral wall of the left ventricle.", "critical"),

    "IPLMI": ConditionInfo("IPLMI", "Inferoposterolateral Myocardial Infarction",
        "Infarction involving the inferior, posterior, and lateral walls.", "critical"),

    "IPMI": ConditionInfo("IPMI", "Inferoposterior Myocardial Infarction",
        "Infarction of the inferior and posterior walls of the left ventricle.", "critical"),

    "PMI": ConditionInfo("PMI", "Posterior Myocardial Infarction",
        "Infarction of the posterior wall, often presenting with tall R waves in V1-V2.", "critical"),

    "QWAVE": ConditionInfo("QWAVE", "Pathological Q Waves",
        "Abnormal Q waves indicating prior myocardial necrosis or infarction.", "warning"),

    # ── Injury patterns ───────────────────────────────────────────────────
    "INJAL": ConditionInfo("INJAL", "Anterolateral Injury",
        "ST elevation pattern in anterolateral leads suggesting acute myocardial injury.", "critical"),

    "INJAS": ConditionInfo("INJAS", "Anteroseptal Injury",
        "ST elevation in anteroseptal leads indicating acute myocardial injury.", "critical"),

    "INJIL": ConditionInfo("INJIL", "Inferolateral Injury",
        "ST elevation in inferolateral leads suggesting acute myocardial injury.", "critical"),

    "INJIN": ConditionInfo("INJIN", "Inferior Injury",
        "ST elevation in inferior leads (II, III, aVF) indicating acute injury.", "critical"),

    "INJLA": ConditionInfo("INJLA", "Lateral Injury",
        "ST elevation in lateral leads indicating acute myocardial injury.", "critical"),

    # ── Ischaemia ─────────────────────────────────────────────────────────
    "ISCAL": ConditionInfo("ISCAL", "Anterolateral Ischaemia",
        "Reduced blood supply to the anterolateral myocardium, shown by ST or T-wave changes.", "critical"),

    "ISCAN": ConditionInfo("ISCAN", "Anterior Ischaemia",
        "Reduced blood supply to the anterior myocardium without full infarction.", "critical"),

    "ISCAS": ConditionInfo("ISCAS", "Anteroseptal Ischaemia",
        "Ischaemic changes in the anteroseptal territory.", "critical"),

    "ISCIL": ConditionInfo("ISCIL", "Inferolateral Ischaemia",
        "Ischaemic changes affecting the inferolateral territory.", "critical"),

    "ISCIN": ConditionInfo("ISCIN", "Inferior Ischaemia",
        "Reduced blood supply to the inferior myocardium.", "critical"),

    "ISCLA": ConditionInfo("ISCLA", "Lateral Ischaemia",
        "Ischaemic changes in the lateral wall territory.", "critical"),

    "ISC_": ConditionInfo("ISC_", "Non-specific Ischaemia",
        "ST or T-wave changes suggesting ischaemia but not localised to a specific territory.", "warning"),

    # ── ST-T changes ──────────────────────────────────────────────────────
    "STTC": ConditionInfo("STTC", "ST-T Change",
        "Non-specific ST segment or T-wave abnormality; may indicate ischaemia, "
        "electrolyte imbalance, or medication effect.", "warning"),

    "NST_": ConditionInfo("NST_", "Non-specific ST Change",
        "Minor ST segment deviation not meeting criteria for ischaemia or infarction.", "warning"),

    "STD_": ConditionInfo("STD_", "ST Depression",
        "ST segment depression, which may indicate subendocardial ischaemia or strain.", "warning"),

    "STE_": ConditionInfo("STE_", "ST Elevation",
        "ST segment elevation above baseline, raising concern for acute myocardial injury or pericarditis.", "critical"),

    "NDT": ConditionInfo("NDT", "Non-diagnostic T-wave Abnormality",
        "T-wave changes that are abnormal but do not meet specific diagnostic criteria. "
        "May reflect ischaemia, electrolyte disturbance, or medication effect.", "warning"),

    "NT_": ConditionInfo("NT_", "Negative T-waves",
        "T-wave inversion in multiple leads, which can indicate ischaemia, ventricular strain, "
        "or be a normal variant in some leads.", "warning"),

    "DIG": ConditionInfo("DIG", "Digitalis Effect",
        "ECG changes (scooped ST depression, short QT) caused by digitalis glycoside medication.", "warning"),

    # ── T-wave abnormalities ──────────────────────────────────────────────
    "INVT": ConditionInfo("INVT", "T-wave Inversion",
        "Negative T-waves in leads where they are normally positive; may indicate "
        "ischaemia or ventricular strain.", "warning"),

    "LOWT": ConditionInfo("LOWT", "Low T-wave Amplitude",
        "Diminished T-wave voltage, which may indicate ischaemia, electrolyte abnormality, "
        "or normal variant.", "warning"),

    "TAB_": ConditionInfo("TAB_", "T-wave Abnormality",
        "General T-wave abnormality not meeting specific diagnostic criteria.", "warning"),

    # ── QT interval ───────────────────────────────────────────────────────
    "LNGQT": ConditionInfo("LNGQT", "Long QT Syndrome",
        "Prolonged QTc interval increasing risk of life-threatening ventricular arrhythmias.", "critical"),

    # ── Hypertrophy ───────────────────────────────────────────────────────
    "LVH": ConditionInfo("LVH", "Left Ventricular Hypertrophy",
        "Thickening of the left ventricular wall, commonly caused by long-standing hypertension.", "warning"),

    "RVH": ConditionInfo("RVH", "Right Ventricular Hypertrophy",
        "Thickening of the right ventricular wall, associated with pulmonary hypertension.", "warning"),

    "VCLVH": ConditionInfo("VCLVH", "Voltage Criteria for LVH",
        "ECG voltage criteria met for left ventricular hypertrophy without other features.", "warning"),

    "HVOLT": ConditionInfo("HVOLT", "High Voltage",
        "Increased QRS amplitude suggesting LVH or a thin chest wall.", "warning"),

    "LVOLT": ConditionInfo("LVOLT", "Low Voltage",
        "Decreased QRS amplitude in all leads; may suggest pericardial effusion, obesity, or COPD.", "warning"),

    "SEHYP": ConditionInfo("SEHYP", "Septal Hypertrophy",
        "Thickening of the interventricular septum, often seen in hypertrophic cardiomyopathy.", "warning"),

    # ── Axis deviations ───────────────────────────────────────────────────
    "LAD": ConditionInfo("LAD", "Left Axis Deviation",
        "Shift of the mean QRS axis left of −30°, often due to fascicular block or LVH.", "warning"),

    "RAD": ConditionInfo("RAD", "Right Axis Deviation",
        "Shift of the mean QRS axis right of +90°, often due to RVH or fascicular block.", "warning"),

    # ── Ventricular ───────────────────────────────────────────────────────
    "PVC": ConditionInfo("PVC", "Premature Ventricular Contraction",
        "An early heartbeat from the ventricles causing a wide, abnormal QRS complex.", "warning"),

    "VTACH": ConditionInfo("VTACH", "Ventricular Tachycardia",
        "Rapid ventricular rhythm (≥ 3 consecutive PVCs at > 100 bpm) — potentially life-threatening.", "critical"),

    "BIGU": ConditionInfo("BIGU", "Bigeminy",
        "Rhythm pattern where every normal beat is followed by a premature beat.", "warning"),

    "TRIGU": ConditionInfo("TRIGU", "Trigeminy",
        "Rhythm pattern where every two normal beats are followed by a premature beat.", "warning"),

    # ── PR interval ───────────────────────────────────────────────────────
    "LPR": ConditionInfo("LPR", "Long PR Interval",
        "PR interval > 200 ms; consistent with first-degree AV block.", "warning"),

    "PRC(S)": ConditionInfo("PRC(S)", "PR Change (Strain)",
        "PR interval changes associated with atrial strain or pericarditis.", "warning"),

    # ── Other / miscellaneous ─────────────────────────────────────────────
    "EL": ConditionInfo("EL", "Electrolyte Disturbance",
        "ECG changes consistent with electrolyte abnormality (e.g. hyperkalaemia, hypokalaemia).", "warning"),

    "ANEUR": ConditionInfo("ANEUR", "Ventricular Aneurysm",
        "Persistent ST elevation pattern suggesting a left ventricular aneurysm from prior MI.", "critical"),
}

_UNKNOWN_CONDITION = ConditionInfo(
    code="UNKNOWN",
    display_name="Unclassified Finding",
    definition="An ECG pattern was detected that does not match a known diagnostic code. "
               "Clinical review is recommended.",
    severity="warning",
)


# ---------------------------------------------------------------------------
# Public helpers
# ---------------------------------------------------------------------------

def get_condition_info(code: str) -> ConditionInfo:
    return _CONDITION_MAP.get(code.upper(), _UNKNOWN_CONDITION)


def map_predictions(
    raw_predictions: dict[str, float],
    top_n: int = 3,
) -> list[dict]:
    """
    Return the top-N predictions sorted by probability, enriched with
    human-readable metadata.
    """
    sorted_preds = sorted(raw_predictions.items(), key=lambda x: x[1], reverse=True)
    top = sorted_preds[:top_n]

    result = []
    for code, prob in top:
        info = get_condition_info(code)
        result.append({
            "code":         info.code if info.code != "UNKNOWN" else code,
            "display_name": info.display_name,
            "definition":   info.definition,
            "probability":  round(float(prob), 4),
            "percentage":   round(float(prob) * 100),
            "severity":     info.severity,
        })
    return result


def get_primary_verdict(
    raw_predictions: dict[str, float],
    threshold: float = 0.5,
) -> dict:
    """
    Return the highest-confidence condition as the headline diagnosis.
    """
    if not raw_predictions:
        return {
            "code": "NORM", "display_name": "Normal ECG",
            "definition": "No significant findings detected.",
            "probability": 0.0, "percentage": 0,
            "severity": "normal", "above_threshold": False,
        }

    top_code, top_prob = max(raw_predictions.items(), key=lambda x: x[1])
    info = get_condition_info(top_code)

    return {
        "code":            info.code if info.code != "UNKNOWN" else top_code,
        "display_name":    info.display_name,
        "definition":      info.definition,
        "probability":     round(float(top_prob), 4),
        "percentage":      round(float(top_prob) * 100),
        "severity":        info.severity,
        "above_threshold": float(top_prob) >= threshold,
    }